site_name: mj-nexara
site_description: Ethical Governance, Financial Sovereignty, and Incorruptible Automation
site_author: MJ Ahmad
repo_url: https://github.com/mj-nexara/mj-nexara
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit

nav:
  - index.md
  - nexara: nexara/index.md
  - nxn-genesis: nxn-genesis/index.md
  - nexaflow: 
      - nexaflow: nexaflow/index.md
  - nexara-protocol: nexara-protocol/index.md
  - nexvote: nexvote/index.md
  - nexdocs: nexdocs/index.md
  - LumID: LumID/index.md
  - NexInvoke: NexInvoke/index.md
  - nexascend: nexascend/index.md
  - EthicBasket: 
      - EthicBasket: EthicBasket/index.md
      - product:
          - service:
              - voiceover: EthicBasket/product/service/voiceover/index.md
  - NexForge: NexForge/index.md
  - NexMark: NexMark/index.md
  - SkyEthix: SkyEthix/index.md
  - my-docs: my-docs/index.md
  - nexaragov-core: nexaragov-core/index.md
  - Docs: Docs/index.md
  - mj: mj/index.md
  - Support:
      - Support: Support/Support.md
  - SystemCleanup: SystemCleanup/index.md
theme:
  name: material
